# Generated by Django 4.1.3 on 2022-11-08 00:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeTypeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elem', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '事業所種別',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.CharField(max_length=32, verbose_name='識別子(事業所番号＠分類コード)')),
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='介護保険事業所番号')),
                ('name', models.CharField(max_length=64, verbose_name='事業所名')),
                ('service_code', models.CharField(max_length=16, verbose_name='介護サービス分類コード')),
                ('postal_code', models.CharField(max_length=16, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=64, verbose_name='事業所所在地')),
                ('phone_number', models.CharField(max_length=16, verbose_name='電話番号')),
                ('fax_number', models.CharField(max_length=16, verbose_name='FAX番号')),
                ('town_code', models.CharField(max_length=16, verbose_name='事業所所在地の市区町村番号')),
                ('longitude', models.IntegerField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='経度')),
                ('latitude', models.IntegerField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='緯度')),
                ('company_name', models.CharField(max_length=64, verbose_name='所属法人名')),
                ('owner', models.CharField(max_length=32, null=True, verbose_name='経営者氏名')),
                ('manager', models.CharField(max_length=32, null=True, verbose_name='責任者氏名')),
                ('capacity_employment', models.IntegerField(verbose_name='定員')),
                ('url', models.CharField(max_length=64, verbose_name='URL')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.officetypeset', verbose_name='法人種別')),
            ],
            options={
                'verbose_name_plural': '事業所',
            },
        ),
    ]
