# Generated by Django 4.1.3 on 2022-11-07 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='事務所コード')),
                ('name', models.CharField(max_length=64, verbose_name='法人名')),
            ],
            options={
                'verbose_name_plural': '事業所',
            },
        ),
        migrations.CreateModel(
            name='OfficeTypeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elem', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '事業所種別',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='office',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.officetypeset', verbose_name='法人種別'),
        ),
    ]
