# Generated by Django 4.1.3 on 2022-11-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_supportapproachset_supportstatusset_supportthemeset_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='capacity_employment',
            new_name='capacity_of_guests',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='code',
            new_name='care_office_code',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='service_code',
            new_name='care_service_code',
        ),
        migrations.AlterField(
            model_name='office',
            name='id',
            field=models.CharField(help_text='介護保険事業所番号_介護サービス分類コード\u3000の半角文字列で構成されます。', max_length=32, verbose_name='識別子'),
        ),
    ]
