# Generated by Django 4.1.3 on 2022-11-14 02:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_capacity_employment_office_capacity_of_guests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='事業所所在地'),
        ),
        migrations.AlterField(
            model_name='office',
            name='capacity_of_guests',
            field=models.IntegerField(blank=True, null=True, verbose_name='定員'),
        ),
        migrations.AlterField(
            model_name='office',
            name='fax',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='FAX番号'),
        ),
        migrations.AlterField(
            model_name='office',
            name='foundation_date',
            field=models.DateField(blank=True, null=True, verbose_name='設立年月日'),
        ),
        migrations.AlterField(
            model_name='office',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='office',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='経度'),
        ),
        migrations.AlterField(
            model_name='office',
            name='manager',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='責任者氏名'),
        ),
        migrations.AlterField(
            model_name='office',
            name='number_of_employees',
            field=models.IntegerField(blank=True, null=True, verbose_name='従業員人数'),
        ),
        migrations.AlterField(
            model_name='office',
            name='owner',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='経営者氏名'),
        ),
        migrations.AlterField(
            model_name='office',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='office',
            name='postal_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='office',
            name='town_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='事業所所在地の市区町村番号'),
        ),
        migrations.AlterField(
            model_name='office',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.officetypeset', verbose_name='法人種別'),
        ),
        migrations.AlterField(
            model_name='office',
            name='url',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='URL'),
        ),
    ]
