# Generated by Django 4.1.3 on 2022-11-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_office_address_alter_office_capacity_of_guests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='company',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='所属法人名'),
        ),
    ]
